name: Build and Release Zen Kernel RPM

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and release'
        required: true
        default: '6.16.8-rpmbuild-v1'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up RPM build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          rpm build-essential bc bison flex \
          libelf-dev libssl-dev zlib1g-dev \
          wget curl git \
          libncurses-dev libudev-dev libpci-dev libiberty-dev autoconf \
          xz-utils cpio

      - name: Prepare rpmbuild directory
        run: |
          mkdir -p $HOME/rpmbuild/{BUILD,BUILDROOT,RPMS,SPECS,SRPMS,SOURCES}
          cp SPECS/kernel-zen.spec $HOME/rpmbuild/SPECS/
          wget https://github.com/Zamanhuseyinli/zenkernel-rpm/releases/download/${{ github.event.inputs.tag }}/linux-zen-6.16.8.tar.gz \
          -O $HOME/rpmbuild/SOURCES/linux-zen-6.16.8.tar.gz


      - name: Build RPM packages
        run: |
          rpmbuild --define "_topdir $HOME/rpmbuild" \
                   -ba $HOME/rpmbuild/SPECS/kernel-zen.spec

      - name: Create GitHub release and upload RPMs
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          files: $HOME/rpmbuild/RPMS/*/*.rpm
