name: Build and Release Zen Kernel RPM

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and release'
        required: true
        default: '6.16.8-rpmbuild-v1'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up RPM build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm build-essential bc bison flex \
            libelf-dev libssl-dev zlib1g-dev gzip

      - name: Prepare rpmbuild directory
        run: |
          mkdir -p $HOME/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
          cp SPECS/kernel-zen.spec $HOME/rpmbuild/SPECS/
          cp SOURCES/linux-zen-*.tar.gz $HOME/rpmbuild/SOURCES/

      - name: Build RPM packages
        run: |
          rpmbuild --define "_topdir $HOME/rpmbuild" \
                   -ba $HOME/rpmbuild/SPECS/kernel-zen.spec

      - name: Create GitHub release and upload RPMs
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          files: $HOME/rpmbuild/RPMS/*/*.rpm
